resolve 04-vue-cli
js-tasks-ru/vue-20220125_belkinalexander pull request #4
Opened 2022-02-12 08:29 UTC by belkinalex

2022-02-12 08:30 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-12 14:49 UTC, ShGKme requested changes
В UiDropdown требуется заменить `selection` на вычисляемое свойство. Осталдьные задачи приняты, Тостер - отлично.

2022-02-12 14:49 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +};
В `mounted` запускается таймер. По-хорошему, чтобы не было утечек и ошибок, лучше не забывать чистить его в `beforeUnmount`. Например, если этот компонент будет уничтожать родитель.

2022-02-12 14:49 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Вместо инициализации `selection` в `data` + обновления при отслеживании, лучше сделать вычисляемое свойство. тогда будет явно видно, что `selection` - не самостоятельные независимые данные состояния, а результат вычисления над другими данными, при этом не придётся думать об отслеживании. Например, сейчас забыли учесть, что `options` потенциально тоже может меняться.

2022-02-12 17:19 UTC, belkinalex commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +};
исправил

2022-02-12 17:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-12 17:19 UTC, belkinalex commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Да, действительно так лучше и проще.
Исправил.

2022-02-12 17:37 UTC, ShGKme reviewed
Все решённые задачи приняты. Но не все добавленные задачи решены.

2022-02-16 19:04 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-16 19:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-16 19:06 UTC, belkinalex commented
Добавил решения для блока 05-vue-router

2022-02-16 19:09 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-16 19:11 UTC, merged